version: '2.3'
services:
    uicore:
        build:
            context: ./uicore
            dockerfile: Dockerfile
        privileged: true
        volumes:
            - ./uicore:/var/www/html
        ports:
            - "80:80"

    tensor:
        build:
            context: ./tensor
        volumes:
            - ./tensor:/magic
            - ./uicore/files:/magic/data
        working_dir: /magic
        runtime:
            nvidia
        ports:
            - "8888:8888"

    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql/database:/var/lib/mysql
        environment:
         - MYSQL_ROOT_PASSWORD=root         
        ports:
         - "3306:3306"