version: '2'
services:
    uicore:
        build:
            context: ./
            dockerfile: Dockerfile
        privileged: true
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"

    mysql:
        image: mysql:5.7
        environment:
         - MYSQL_ROOT_PASSWORD=root         
        ports:
         - "3306:3306"