version: '2'
services:
    uicore:
        build:
            context: ./uicore
            dockerfile: Dockerfile
        privileged: true
        volumes:
            - ./uicore:/var/www/html
        ports:
            - "80:80"

#    tensor:
#        image: tensorflow/tensorflow:latest-gpu-jupyter
#        ports:
#            - "8888:8888"

    mysql:
        image: mysql:5.7
        environment:
         - MYSQL_ROOT_PASSWORD=root         
        ports:
         - "3306:3306"